package parser;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.misc.ParseCancellationException;

import calculator.Expression;
import parser.antlr.ExprLexer;
import parser.antlr.ExprParser;
import parser.exceptions.IllegalConstructionRuntime;
import parser.exceptions.ParsingException;

/**
 * A parser class for converting arithmetic expressions from strings into {@link Expression} objects.
 * This parser uses a visitor implementation ({@link ExprVisitorImpl}) to traverse the parse tree generated by ANTLR.
 */
public class Parser {

    /**
     * The visitor used to traverse the parse tree and generate an {@link Expression}.
     */
    private ExprVisitorImpl visitor = new ExprVisitorImpl();

    /**
     * The error listener used to throw an exception when an error occurs during parsing.
     */
    private ErrorListener errorListener = new ErrorListener();

    /**
     * Parses a string arithmetic expression and returns its corresponding {@link Expression} object.
     *
     * @param input The mathematical expression as a string.
     * @return The parsed {@link Expression} representing the input.
     * @throws ParsingException If an error occurs during parsing.
     */
    public Expression parse(String input) throws ParsingException {

        ExprLexer lexer = new ExprLexer(CharStreams.fromString(input));
        lexer.removeErrorListeners();
        lexer.addErrorListener(errorListener);

        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExprParser parser = new ExprParser(tokens);
        parser.removeErrorListeners();
        parser.addErrorListener(errorListener);

        try {
            return visitor.visit(parser.completeExpr());
        } catch (ParseCancellationException | IllegalArgumentException | IllegalConstructionRuntime e) {
            throw new ParsingException(e.getMessage());
        }
    }
}
