name: continuous-reporting

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

permissions:
  contents: write # Needed to upload assets to the release

jobs:
  generate-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Generate and Upload Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Reports(JavaDoc, Coverage, PMD)
        run: mvn verify

      - name: Archive reports
        run: |
          mkdir -p reports
          mkdir -p reports/javadoc
          mkdir -p reports/jacoco
          mkdir -p reports/cucumber

          # JavaDoc
          cp -r target/reports/apidocs/* reports/javadoc

          # Cucumber tests
          cp -r target/reports/surefire/* reports/cucumber

          # JaCoCo Coverage
          cp -r target/site/jacoco/* reports/jacoco

          # PMD Report
          cp target/pmd.xml reports/pmd.xml

          # Compress everything
          zip -r reports.zip reports

      - name: Get latest release info
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            if (releases.data.length > 0) {
              const latest = releases.data[0];
              core.setOutput("tag_name", latest.tag_name);
            } else {
              core.setOutput("tag_name", "");
            }

      - name: Upload report to latest release (if exists)
        if: steps.get_release.outputs.id != ''
        uses: softprops/action-gh-release@v1
        with:
          files: reports.zip
          tag_name: ${{ steps.get_release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
