name: continuous-reporting

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
  release:
    types:
      - published

permissions:
  contents: write # Needed to upload assets to the release

jobs:
  generate-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Generate and Upload Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Reports (JavaDoc, Coverage, PMD)
        run: mvn verify

      - name: Archive reports
        run: |
          mkdir -p reports
          mkdir -p reports/javadoc
          mkdir -p reports/jacoco

          # JavaDoc
          cp -r target/reports/apidocs/* reports/javadoc

          # JaCoCo Coverage
          cp -r target/site/jacoco/* reports/jacoco

          # PMD Report
          cp target/pmd.xml reports/pmd.xml

          # Compress everything
          zip -r reports.zip reports

      - name: Set release tag (if exists)
        if: github.event.release != null
        run: echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Upload report to release
        if: github.event.release != null
        uses: softprops/action-gh-release@v1
        with:
          files: reports.zip
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
