name: continuous-reporting

on:
  release:
    types: [published]

permissions:
  contents: write  # Needed to upload or delete release assets and tags

jobs:
  verify-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run mvn verify
        id: verify
        run: mvn clean verify
        continue-on-error: true  # Capture test failure but continue workflow

      - name: Delete release if verify failed
        if: steps.verify.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # PAT required
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "Tests failed. Deleting release $TAG_NAME..."

          gh release delete "$TAG_NAME" --yes
          git push origin --delete "$TAG_NAME"

      - name: Archive reports
        if: steps.verify.outcome == 'success'
        run: |
          mkdir -p reports/javadoc reports/jacoco reports/surefire-reports

          cp -r target/report/apidocs/* reports/javadoc || true
          cp -r target/surefire-report/* reports/surefire-reports || true
          cp -r target/site/jacoco/* reports/jacoco || true
          cp target/reports/pmd.html reports/pmd.html || true

          zip -r reports.zip reports

      - name: Upload reports to release
        if: steps.verify.outcome == 'success'
        uses: softprops/action-gh-release@v1
        with:
          files: reports.zip
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Fail workflow if tests failed
        if: steps.verify.outcome == 'failure'
        run: |
          echo "❌ mvn verify failed. Workflow failed."
          exit 1
