name: Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven (including running all tests)
        run: mvn -B package --file pom.xml

      - name: Upload Maven completion artifact
        uses: actions/upload-artifact@v2
        with:
          name: maven-completion
          path: target/