# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed


permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  pmd-code-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: PMD code scan
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      #actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871
      - run: git branch
      - name: Set up JDK 23
        uses: actions/setup-java@799ee7c97e9721ef38d1a7e8486c39753b9d6102
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@1e12f89d3b1f899c03c8053cf35ca345d9ee8194
        with:
          rulesets: |
            rulesets/java/quickstart.xml,
            category/java/errorprone.xml,
            category/java/security.xml,
            category/java/bestpractices.xml,

          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      - name: Continuous build if there are violations but prints warning
        if: steps.pmd.outputs.violations != 0
        run: echo "PMD found violations, but continuing..."
