name: PMD

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run PMD
        run: mvn pmd:pmd